### ISSUE TITLE
VectorMixin

### ISSUE THREAD

**Issue by cgarciae** [google/tree-math#3]
Hey! Continuing the [discussion](https://twitter.com/cgarciae88/status/1476216569873276936) about VectorMixin for pytree classes, I see two ways to implement this:

1. `VectorMixin` inherits from `Vector` and overrides the `tree` property to return `self`. Roughly implemented as:

```python
class VectorMixin(tm.Vector):
    """A mixin class for vector operations that works with any pytree class"""

    @property
    def tree(self):
        return self
```

2. `VectorMixin` does not inherit from `Vector`, instead of using `.tree` it assumes `self` is a pytree and implements all the operators based on this. `Vector` inherits from `VectorMixin` and implements the pytree protocol roughly as:

```python
@tree_util.register_pytree_node_class
class Vector(VectorMixin):
  """A wrapper for treating an arbitrary pytree as a 1D vector."""

  def __init__(self, tree):
    self._tree = tree

  def tree_flatten(self):
    return (self._tree,), None

  @classmethod
  def tree_unflatten(cls, _, args):
    return cls(*args)
  
  ...
```

First option is the easiest, second requires a refactor but its more in the spirit of what a mixin "should be". WDYT?

**Comment by shoyer** [comment]
Great question! The second version does feel a little more "right" to me from an OO perspective, since it avoids redundantly defining methods.

The main complication is with type checking. If we take option (2) then type checking for tree-math compatible vectors should always use `VectorMixin`. That feels slightly more awkward for users, but is probably a worthwhile tradeoff (and certainly is better than using magic to make `isinstance(..., Vector)` work).

**Comment by cgarciae** [comment]
Good point, maybe we could consider `VectorBase` or something that sounds better for type checking.

**Comment by shoyer** [comment]
Thanks for the PR!

One complexity with VectorMixin that only occurs to me now is how it should interact with the `Matrix` class (https://github.com/google/tree-math/issues/6).

In particular: what should happen when you stack together a bunch of `VectorMixin` vector into a matrix? If we still want indexing into the Matrix to return a `VectorMixin` object (as opposed to a VectorMixin wrapped in a Vector), we will probably need Matrix to be aware of VectorMixin and/or possibly make VectorMixin more general (TreeMathMixin?) to handle multi-dimensional inputs.

I guess the simplest option would be to defer this question for now and make `Matrix` only work with `Vector` objects.

**Comment by cgarciae** [comment]
Been trying to grasp the implications of `Matrix` vs `Vector`. I believe it could follow the same recipe: have a `MatrixMixin` with the basic behavior and a `Matrix` class which works as a wrapper over a pytree. Only `MatrixMixin` should know about `VectorMixin` and vice versa.

I guess time will tell but if we want to go beyond 2D then maybe having a single `TreeMathMixin` class  (`NDArrayMixing` sounds better) would be more convenient.

**Comment by shoyer** [comment]
I'm going ot mark this one as closed for now, given that we merged in VectorMixin.
