### ISSUE TITLE
Rename wrap/unwrap?

### ISSUE THREAD

**Issue by shoyer** [google/tree-math#5]
These are rather undescriptive names, and I guess most people (including myself!) will have to guess & check to keep them straight. :)

Some other possibilities, in rough order of increasing descriptiveness:

- tree_wrap/tree_unwrap
- transform/untransform
- automath/undomath
- vectorize/unvectorize
- tree_vectorize/tree_unvectorize
- vector_to_tree_func/tree_to_vector_func

Any favorites?

**Comment by soraros** [comment]
The `wrap/unwrap` names alone are not very infomatie, but `tree_math.wrap/unwrap` are. Some of the names listed above even look redundant in the quantified form.

**Comment by shoyer** [comment]
These names are probably good enough for now :)
